const GET_FILES_PAGINATED = "GET_FILES_PAGINATED";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const SET_WAIT = "SET_WAIT";
const UNSET_WAIT = "UNSET_WAIT";
const UPDATE_PROGRESS = "UPDATE_PROGRESS";
const UNSET_PROGRESS = "UNSET_PROGRESS";
export {
  GET_FILES_PAGINATED,
  SET_ALERT,
  REMOVE_ALERT,
  SET_WAIT,
  UNSET_PROGRESS,
  UNSET_WAIT,
  UPDATE_PROGRESS,
};
